language: node_js
node_js:
cache:
  directories:
  - node_modules
script:
  - npm run build
deploy:
  - provider: pages
    github_token: $GITHUB_TOKEN
    local_dir: ./build/
    skip_cleanup: true
  - provider: surge
    project: ./build/
    skip_cleanup: true
